### PR TITLE
Updated index.html,create_DB.html,create_table.html

### PR DESCRIPTION
**Pull request by Anki-ta**
Just added Alter,drop,truncate under DDL in the menubar.

### CODE REVIEW

**Comment by raitDB** [comment]
alter me bhi drop hai aur waise bhi drop hai drop ek he hona cahiye.....

**Comment by Anki-ta** [comment]
Alter-Drop is used for dropping  specific columns in a table n vo dusra Drop is used for dropping tables

**Comment by raitDB** [comment]
Then usi drop me specific column drop karne ka option de dege agar do drop hoga to user  confuse ho sakta hai dusre drop me 2 option hoge drop table  aur drop database uske bad drop table me jo table select karega user usme coulum ke yaha check box dikha dege to agar user ko pura table drop karna hoga to wo pura table drop karega warna specific column select kar ke usko drop kar dega.....

**Comment by raitDB** [comment]
Maine tera code test kar liya hai....Mai merge kar deta hai tera request bad me change kar dege jabhi drop ka banayege...........

**Comment by Anki-ta** [comment]
haa waise confusion hoskta hai user ko but drop column is a part of alter command so it should remain under alter section.We can modify that in this way :ALTER-->add column,modify column,drop column. And for the other ddl command : Drop--->Table,Database

**Pull request merged**
